task2/mysite/mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('todolist.urls')),
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

task2/mysite/todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:affair_id>/doer/', views.doer, name='doer'),
    path('adder/', views.adder, name='adder')
]

task2/mysite/todolist/models.py
from django.db import models

# Create your models here.


class Affair(models.Model):
    affair_text = models.CharField(max_length=300)
    pub_date = models.DateTimeField('date published')
    is_done = models.BooleanField(default=False)

    def __str__(self):
        return self.affair_text

task2/mysite/todolist/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from .models import Affair


def index(request):
    active_affairs = Affair.objects.filter(is_done=False)
    inactive_affairs = Affair.objects.filter(is_done=True)
    context = {'active_affairs': active_affairs,
               'inactive_affairs': inactive_affairs}
    return render(request, 'todolist/index.html', context)


def doer(request, affair_id):
    affair = get_object_or_404(Affair, pk=affair_id)
    try:
        action = request.POST['doer']
    except KeyError:
        return HttpResponseRedirect(reverse('todolist:index'))
    else:
        if action == 'Done!' or action == 'Undone!':
            affair.is_done = not affair.is_done
            affair.save()
        return HttpResponseRedirect(reverse('todolist:index'))


def adder(request):
    try:
        affair_text_ = request.POST['new_affair']
        new_affair = Affair(affair_text=affair_text_, pub_date=timezone.now())
        new_affair.save()
        return HttpResponseRedirect(reverse('todolist:index'))
    except KeyError:
        return HttpResponseRedirect(reverse('todolist:index'))

task2/mysite/todolist/templates/todolist/index.html
<html>
    <head>
        <title>My toDoList</title>
    </head>
    <body>
        <h1>We are happy to introduce you to toDoList 1.0</h1>
        <h2>List of active affairs:</h2>
        {% if active_affairs %}
            <ul>
            {% for affair in active_affairs %}
                <li>
                    <a>{{ affair.affair_text }}
                        <form action="{% url 'todolist:doer' affair.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" name="doer" id="doer{{ affair.id }}" value="Done!" />
                        </form>
                    </a>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No active affairs are available.</p>
        {% endif %}

        <h2>List of completed affairs:</h2>
        {% if inactive_affairs %}
            <ul>
            {% for affair in inactive_affairs %}
                <li>
                    <a>{{ affair.affair_text }}</a>
                    <form action="{% url 'todolist:doer' affair.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" name="doer" id="doer{{ affair.id }}" value="Undone!" />
                    </form>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No inactive affairs are available.</p>
        {% endif %}

        <h2> Add new affairs: </h2>
        <form action="{% url 'todolist:adder'%}" method="post">
        {% csrf_token %}
        <label for="new_affair">New affair: </label>
        <input id="new_affair" type="text" name="new_affair" value="{{ new_affair_text }}">
        <input type="submit" value="OK">
        </form>
    </body>
</html>